name: cross build for OpenBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://cdn.openbsd.org/pub/OpenBSD/
        target-version: ['7.2', '7.3', '7.4']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update

      - run: |
          ~/.uppm/installed/gsed/bin/gsed -i '/git-url/a git-sha: ${{ github.sha }}' ~/.ppkg/repos.d/official-core/formula/autotools-setup.yml

      - run: ./ppkg install openbsd-${{ matrix.target-version }}-amd64/autotools-setup --link-type=static-most
      - run: ./ppkg pack    openbsd-${{ matrix.target-version }}-amd64/autotools-setup
