name: cross build for FreeBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://archive.freebsd.org/old-releases/amd64/
        target-version: ['13.0', '13.1', '13.2']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update

      - run: |
          ~/.uppm/installed/gsed/bin/gsed -i '/git-url/a git-sha: ${{ github.sha }}' ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

      - run: ./ppkg install freebsd-${{ matrix.target-version }}-amd64/autotools-setup --link-type=static-full
      - run: ./ppkg pack    freebsd-${{ matrix.target-version }}-amd64/autotools-setup
