name: cross build for NetBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://ftp.netbsd.org/pub/NetBSD/
        target-version: ['9.1', '9.2', '9.3']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update

      - run: |
          ~/.uppm/installed/gsed/bin/gsed -i '/git-url/a git-sha: ${{ github.sha }}' ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

      - run: ./ppkg install netbsd-${{ matrix.target-version }}-amd64/autotools-setup --link-type=static-full
      - run: ./ppkg pack    netbsd-${{ matrix.target-version }}-amd64/autotools-setup
