name: Debian GNU/Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['9.13', '10.7', '11.5']

    container: debian:${{ matrix.tag }}

    steps:
      - run:  id
      - run:  apt -y update
      - run:  apt -y install curl g++ xz-utils

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install autotools-setup


      - run:  echo "SSL_CERT_FILE=$HOME/.ppkg/core/etc/ssl/certs/cacert.pem" >> $GITHUB_ENV

      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup

      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup --help
      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup -h

      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup --version
      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup -V

      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup sysinfo

      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup env

      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup integrate zsh

      - run:  ~/.ppkg/installed/autotools-setup/bin/autotools-setup setup -v
