name: LinuxMint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: [19.3, 20.1]

    container: linuxmintd/mint${{ matrix.tag }}-amd64

    steps:
      - run:  id
      - run:  sudo apt -y update
      - run:  sudo apt -y install curl xz-utils g++

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install autotools-setup


      - run:  echo "SSL_CERT_FILE=$HOME/.ppkg/core/etc/ssl/certs/cacert.pem" >> $GITHUB_ENV


      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup

      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup --help
      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup -h

      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup --version
      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup -V

      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup sysinfo

      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup env

      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup show-default-config

      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup integrate zsh
      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup integrate zsh -v

      - run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup setup -v

      - uses: actions/checkout@v3
        with:
          repository: universal-ctags/ctags
          path: ctags

      - run: |
          unset IFS

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "$*"
          }

          run() {
              echo "${COLOR_PURPLE}==>${COLOR_OFF} ${COLOR_GREEN}$@${COLOR_OFF}"
              eval "$*"
          }

          run source ~/.autotools-setup/autotools/env.sh

          run cd ctags

          run ./autogen.sh
          run ./configure --prefix=$PWD/out
          run gmake
          run gmake install

       #- run: ~/.ppkg/installed/autotools-setup/bin/autotools-setup upgrade-self
