name: macos

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  brew:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - run:  brew update
      - run:  brew install --overwrite python@3.10 python@3.11 python@3.12
      - run:  brew install cmake ninja pkg-config curl libyaml libarchive

      - run: sed -i '.bak' '/Requires.private:/d' "$(brew --prefix libarchive)/lib/pkgconfig/libarchive.pc"

      - run:  |
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig"
          CMAKE_EXE_LINKER_FLAGS='-L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -lssl -liconv -framework CoreFoundation -framework Security'
          CMAKE_FIND_ROOT_PATH="$(brew --prefix openssl@1.1);$(brew --prefix curl);$(brew --prefix libarchive)"

          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS" \
              -DCMAKE_FIND_ROOT_PATH="$CMAKE_FIND_ROOT_PATH"

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/autotools-setup

      - run: ./output/bin/autotools-setup --help
      - run: ./output/bin/autotools-setup -h

      - run: ./output/bin/autotools-setup --version
      - run: ./output/bin/autotools-setup -V

      - run: ./output/bin/autotools-setup sysinfo

      - run: ./output/bin/autotools-setup env

      - run: ./output/bin/autotools-setup config

      - run: ./output/bin/autotools-setup integrate zsh
      - run: ./output/bin/autotools-setup integrate zsh -v

      - run: ./output/bin/autotools-setup setup -v

      - uses: actions/checkout@v3
        with:
          repository: universal-ctags/ctags
          path: ctags

      - run: |
          unset IFS

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "$*"
          }

          run() {
              echo "${COLOR_PURPLE}==>${COLOR_OFF} ${COLOR_GREEN}$@${COLOR_OFF}"
              eval "$*"
          }

          run . ~/.autotools-setup/autotools/env.sh

          run cd ctags

          run ./autogen.sh
          run ./configure --prefix=$PWD/out
          run gmake
          run gmake install

       #- run: ./output/bin/autotools-setup upgrade-self


  vcpkg:

    strategy:
      fail-fast: false
      matrix:
        version: [macos-11, macos-12]

    runs-on: ${{ matrix.version }}

    steps:
      - run:  brew update
      - run:  brew install cmake ninja pkg-config

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install curl openssl libarchive libyaml

      - run:  |
          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/autotools-setup

      - run: ./output/bin/autotools-setup --help
      - run: ./output/bin/autotools-setup -h

      - run: ./output/bin/autotools-setup --version
      - run: ./output/bin/autotools-setup -V

      - run: ./output/bin/autotools-setup sysinfo

      - run: ./output/bin/autotools-setup env

      - run: ./output/bin/autotools-setup config

      - run: ./output/bin/autotools-setup integrate zsh
      - run: ./output/bin/autotools-setup integrate zsh -v

      - run: ./output/bin/autotools-setup setup -v

      - uses: actions/checkout@v3
        with:
          repository: universal-ctags/ctags
          path: ctags

      - run: |
          unset IFS

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "$*"
          }

          run() {
              echo "${COLOR_PURPLE}==>${COLOR_OFF} ${COLOR_GREEN}$@${COLOR_OFF}"
              eval "$*"
          }

          run . ~/.autotools-setup/autotools/env.sh

          run cd ctags

          run ./autogen.sh
          run ./configure --prefix=$PWD/out
          run gmake
          run gmake install

       #- run: ./output/bin/autotools-setup upgrade-self


  vcpkg-sanitizer:

    strategy:
      fail-fast: false
      matrix:
        version: [macos-11, macos-12]

    runs-on: ${{ matrix.version }}

    steps:
      - run:  brew update
      - run:  brew install --overwrite python@3.10 python@3.11
      - run:  brew install cmake ninja llvm pkg-config

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install curl openssl libarchive libyaml

      - run:  |
          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
              -DCMAKE_C_FLAGS="-fsanitize=undefined -fsanitize=address -fsanitize=leak"

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/autotools-setup

      - run: ./output/bin/autotools-setup --help
      - run: ./output/bin/autotools-setup -h

      - run: ./output/bin/autotools-setup --version
      - run: ./output/bin/autotools-setup -V

      - run: ./output/bin/autotools-setup sysinfo

      - run: ./output/bin/autotools-setup env

      - run: ./output/bin/autotools-setup config

      - run: ./output/bin/autotools-setup integrate zsh
      - run: ./output/bin/autotools-setup integrate zsh -v

      - run: ./output/bin/autotools-setup setup -v

      - uses: actions/checkout@v3
        with:
          repository: universal-ctags/ctags
          path: ctags

      - run: |
          unset IFS

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "$*"
          }

          run() {
              echo "${COLOR_PURPLE}==>${COLOR_OFF} ${COLOR_GREEN}$@${COLOR_OFF}"
              eval "$*"
          }

          run . ~/.autotools-setup/autotools/env.sh

          run cd ctags

          run ./autogen.sh
          run ./configure --prefix=$PWD/out
          run gmake
          run gmake install

       #- run: ./output/bin/autotools-setup upgrade-self


  brew-sanitizer:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - run:  brew update
      - run:  brew install --overwrite python@3.10 python@3.11
      - run:  brew install cmake ninja llvm pkg-config curl libyaml libarchive

      - run: sed -i '.bak' '/Requires.private:/d' "$(brew --prefix libarchive)/lib/pkgconfig/libarchive.pc"

      - run:  |
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig"
          CMAKE_EXE_LINKER_FLAGS='-L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -lssl -liconv -framework CoreFoundation -framework Security'
          CMAKE_FIND_ROOT_PATH="$(brew --prefix openssl@1.1);$(brew --prefix curl);$(brew --prefix libarchive)"

          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS" \
              -DCMAKE_FIND_ROOT_PATH="$CMAKE_FIND_ROOT_PATH" \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
              -DCMAKE_C_FLAGS="-fsanitize=undefined -fsanitize=address -fsanitize=leak"

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/autotools-setup

      - run: ./output/bin/autotools-setup --help
      - run: ./output/bin/autotools-setup -h

      - run: ./output/bin/autotools-setup --version
      - run: ./output/bin/autotools-setup -V

      - run: ./output/bin/autotools-setup sysinfo

      - run: ./output/bin/autotools-setup env

      - run: ./output/bin/autotools-setup config

      - run: ./output/bin/autotools-setup integrate zsh
      - run: ./output/bin/autotools-setup integrate zsh -v

      - run: ./output/bin/autotools-setup setup -v

      - uses: actions/checkout@v3
        with:
          repository: universal-ctags/ctags
          path: ctags

      - run: |
          unset IFS

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "$*"
          }

          run() {
              echo "${COLOR_PURPLE}==>${COLOR_OFF} ${COLOR_GREEN}$@${COLOR_OFF}"
              eval "$*"
          }

          run . ~/.autotools-setup/autotools/env.sh

          run cd ctags

          run ./autogen.sh
          run ./configure --prefix=$PWD/out
          run gmake
          run gmake install

       #- run: ./output/bin/autotools-setup upgrade-self
