name: build with xcpkg on macOS

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  xcpkg:

    strategy:
      fail-fast: false
      matrix:
        version: [macos-13, macos-12]
        target: [ 'MacOSX-10.15-x86_64', 'MacOSX-11.0-x86_64', 'MacOSX-12.0-x86_64', 'MacOSX-13.0-x86_64',  'MacOSX-11.0-arm64', 'MacOSX-12.0-arm64', 'MacOSX-13.0-arm64']

    runs-on: ${{ matrix.version }}

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg setup
      - run: ./xcpkg update

      - run: |
          ~/.uppm/installed/gsed/bin/gsed -i '/^git-url:/a git-sha: ${{ github.sha }}' ~/.xcpkg/repos.d/offical-core/formula/autotools-setup.yml

      - run: ./xcpkg install    ${{ matrix.target }}/autotools-setup --link-type=static-prefered --install-lib=static

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup --help
      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup -h

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup --version
      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup -V

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup env

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup buildinfo

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup sysinfo

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup config

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup integrate zsh
      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup integrate zsh -v

      - run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup setup -v

      - uses: actions/checkout@v3
        with:
          repository: universal-ctags/ctags
          path: ctags

      - run: |
          unset IFS

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "$*"
          }

          run() {
              echo "${COLOR_PURPLE}==>${COLOR_OFF} ${COLOR_GREEN}$@${COLOR_OFF}"
              eval "$*"
          }

          run . ~/.autotools-setup/autotools/env.sh

          run cd ctags

          run ./autogen.sh
          run ./configure --prefix=$PWD/out
          run gmake
          run gmake install

       #- run: ~/.xcpkg/installed/${{ matrix.target }}/autotools-setup/bin/autotools-setup upgrade-self
