name: NetBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: macos-12
    
    strategy:
      fail-fast: false
      matrix:
        version: [9]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-generic-netbsd-${{ matrix.version }}
          restore-keys: |
            vagrant-generic-netbsd-${{ matrix.version }}

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/netbsd${{ matrix.version }}
          run: |
            run sudo pkgin -y install cmake ninja-build pkg-config clang curl libarchive libyaml

            run cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
            run cmake --build   build.d
            run cmake --install build.d


            export LD_LIBRARY_PATH=/usr/pkg/lib

            run sudo rm -rf /usr/pkg/etc/openssl
            run sudo pkgin -y install mozilla-rootcerts
            run sudo mozilla-rootcerts install

            if [ ${{matrix.version}} -eq 8 ] ; then
                export SSL_CERT_FILE=/usr/pkg/etc/openssl/certs/ca-certificates.crt
            else
                export SSL_CERT_FILE=/etc/openssl/certs/ca-certificates.crt
            fi


            run ./output/bin/autotools-setup

            run ./output/bin/autotools-setup --help
            run ./output/bin/autotools-setup -h

            run ./output/bin/autotools-setup --version
            run ./output/bin/autotools-setup -V

            run ./output/bin/autotools-setup sysinfo

            run ./output/bin/autotools-setup env

            run ./output/bin/autotools-setup config

            run ./output/bin/autotools-setup integrate zsh
            run ./output/bin/autotools-setup integrate zsh -v

            run ./output/bin/autotools-setup setup -v

            run . ~/.autotools-setup/autotools/env.sh

            run sudo pkgin -y install git

            run git clone --depth=1 https://github.com/universal-ctags/ctags

            run cd ctags

            run ./autogen.sh
            run ./configure --prefix=$PWD/out
            run gmake
            run gmake install


           #run ./output/bin/autotools-setup upgrade-self
