name: OpenBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: macos-12
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-generic-openbsd-7
          restore-keys: |
            vagrant-generic-openbsd-7

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/openbsd7
          run: |
            run sudo pkg_add cmake ninja llvm pkgconf curl libarchive libyaml

            run cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
            run cmake --build   build.d
            run cmake --install build.d


            run ./output/bin/autotools-setup

            run ./output/bin/autotools-setup --help
            run ./output/bin/autotools-setup -h

            run ./output/bin/autotools-setup --version
            run ./output/bin/autotools-setup -V

            run ./output/bin/autotools-setup sysinfo

            run ./output/bin/autotools-setup env

            run ./output/bin/autotools-setup show-default-config

            run ./output/bin/autotools-setup integrate zsh
            run ./output/bin/autotools-setup integrate zsh -v

            run ./output/bin/autotools-setup setup -v

            run source ~/.autotools-setup/autotools/env.sh

            run sudo pkg_add git

            run git clone https://github.com/universal-ctags/ctags

            run cd ctags

            run ./autogen.sh
            run ./configure --prefix=$PWD/out
            run gmake
            run gmake install


           #run ./output/bin/autotools-setup upgrade-self
