name: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:

  check:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - id:  check-if-has-new-commit
        run: |
          cat > QUERY <<EOF
          {
            repository(owner: "leleliu008", name: "autotools-setup") {
                latestRelease {
                  name
                }
            }
          }
          EOF

          LATEST_RELEASE_GIT_SHA="$(gh api graphql -f "query=$(cat QUERY)" --jq .data.repository.latestRelease.name | cut -d+ -f2)"

          printf 'LATEST_RELEASE_GIT_SHA=%s\n' "$LATEST_RELEASE_GIT_SHA"

          CURRENT_SOURCE_GIT_SHA=${{ github.sha }}

          printf 'CURRENT_SOURCE_GIT_SHA=%s\n' "$CURRENT_SOURCE_GIT_SHA"


          if [ "$LATEST_RELEASE_GIT_SHA" = "$CURRENT_SOURCE_GIT_SHA" ] ; then
              printf 'HAS_NEW_COMMIT=no\n'        >> "$GITHUB_OUTPUT"
          else
              printf 'HAS_NEW_COMMIT=yes\n'       >> "$GITHUB_OUTPUT"
          fi

          printf 'GIT_SHA=%s\n' "$CURRENT_SOURCE_GIT_SHA" >> "$GITHUB_OUTPUT"

    outputs:
      if-has-new-commit: ${{ steps.check-if-has-new-commit.outputs.HAS_NEW_COMMIT }}
      git-sha:           ${{ steps.check-if-has-new-commit.outputs.GIT_SHA }}


  netbsd-amd64:
    needs: [check]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://ftp.netbsd.org/pub/NetBSD/
        target-version: ['9.1', '9.2', '9.3']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update

      - run: |
          ~/.uppm/installed/gsed/bin/gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

      - run: ./ppkg install netbsd-${{ matrix.target-version }}-amd64/autotools-setup --link-type=static-full
      - run: ./ppkg pack    netbsd-${{ matrix.target-version }}-amd64/autotools-setup

      - uses: actions/upload-artifact@v3
        with:
          name: autotools-setup---netbsd-${{ matrix.target-version }}-amd64-tar-xz
          path: autotools-setup-*-netbsd-${{ matrix.target-version }}-amd64.tar.xz

  openbsd-amd64:
    needs: [check, netbsd-amd64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://cdn.openbsd.org/pub/OpenBSD/
        target-version: ['7.2', '7.3', '7.4']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update

      - run: |
          ~/.uppm/installed/gsed/bin/gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

      - run: ./ppkg install openbsd-${{ matrix.target-version }}-amd64/autotools-setup --link-type=static-most
      - run: ./ppkg pack    openbsd-${{ matrix.target-version }}-amd64/autotools-setup

      - uses: actions/upload-artifact@v3
        with:
          name: autotools-setup---openbsd-${{ matrix.target-version }}-amd64-tar-xz
          path: autotools-setup-*-openbsd-${{ matrix.target-version }}-amd64.tar.xz

  freebsd-amd64:
    needs: [check, openbsd-amd64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://archive.freebsd.org/old-releases/amd64/
        target-version: ['13.0', '13.1', '13.2']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: ./ppkg update

      - run: |
          ~/.uppm/installed/gsed/bin/gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

      - run: ./ppkg install freebsd-${{ matrix.target-version }}-amd64/autotools-setup --link-type=static-full
      - run: ./ppkg pack    freebsd-${{ matrix.target-version }}-amd64/autotools-setup

      - uses: actions/upload-artifact@v3
        with:
          name: autotools-setup---freebsd-${{ matrix.target-version }}-amd64-tar-xz
          path: autotools-setup-*-freebsd-${{ matrix.target-version }}-amd64.tar.xz


  macos:
    needs: [check, freebsd-amd64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        target-version: ['11.0', '12.0', '13.0']
        target-arch: [x86_64, arm64]

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg setup
      - run: ./xcpkg update

      - run: |
          gsed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.xcpkg/repos.d/offical-core/formula/autotools-setup.yml

      - run: ./xcpkg install MacOSX/${{ matrix.target-version }}/${{ matrix.target-arch }}/autotools-setup --link-type=static-prefered --install-lib=static
      - run: ./xcpkg pack    MacOSX/${{ matrix.target-version }}/${{ matrix.target-arch }}/autotools-setup -o .

      - uses: actions/upload-artifact@v3
        with:
          name: autotools-setup---macos${{ matrix.target-version }}-${{ matrix.target-arch }}-tar-xz
          path: autotools-setup-*-macos*.tar.xz


  linux-x86_64:
    needs: [check, macos]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    container: alpine:3.18

    steps:
      - run: wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup --use-system-package-manager
      - run: ./ppkg update

      - run: |
          sed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

      - run: ./ppkg install autotools-setup --link-type=static-full
      - run: ./ppkg pack    autotools-setup -o .

      - uses: actions/upload-artifact@v3
        with:
          name: autotools-setup---linux-x86_64-tar-xz
          path: autotools-setup-*-linux-x86_64.tar.xz


  linux-aarch64:
    needs: [check, linux-x86_64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          run chmod a+x ppkg
          run ./ppkg setup --use-system-package-manager
          run ./ppkg update

          sed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

          run ./ppkg install autotools-setup gh --link-type=static-full
          run ./ppkg pack    autotools-setup -o .
          EOF

          chmod +x run.sh

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v $PWD:$PWD -w $PWD --name alpine arm64v8/alpine sh run.sh

      - run: ls

      - uses: actions/upload-artifact@v3
        with:
          name: autotools-setup---linux-aarch64-tar-xz
          path: autotools-setup-*-linux-aarch64.tar.xz


  linux-ppc64le:
    needs: [check, linux-aarch64]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          run chmod a+x ppkg
          run ./ppkg setup --use-system-package-manager
          run ./ppkg update

          sed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

          run ./ppkg install autotools-setup gh --link-type=static-full
          run ./ppkg pack    autotools-setup -o .
          EOF

          chmod +x run.sh

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v $PWD:$PWD -w $PWD --name alpine ppc64le/alpine sh run.sh

      - run: ls

      - uses: actions/upload-artifact@v3
        with:
          name: autotools-setup---linux-ppc64le-tar-xz
          path: autotools-setup-*-linux-ppc64le.tar.xz


  linux-s390x:
    needs: [check, linux-ppc64le]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          run chmod a+x ppkg
          run ./ppkg setup --use-system-package-manager
          run ./ppkg update

          sed -i "/git-url/a git-sha: ${{ needs.check.outputs.git-sha }}" ~/.ppkg/repos.d/offical-core/formula/autotools-setup.yml

          run ./ppkg install autotools-setup gh --link-type=static-full
          run ./ppkg pack    autotools-setup -o .
          EOF

          chmod +x run.sh

      # https://github.com/multiarch/qemu-user-static
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run -v $PWD:$PWD -w $PWD --name alpine s390x/alpine sh run.sh

      - run: ls

      - uses: actions/upload-artifact@v3
        with:
          name: autotools-setup---linux-s390x-tar-xz
          path: autotools-setup-*-linux-s390x.tar.xz


  publish:
    needs: [check, linux-s390x]
    if: needs.check.outputs.if-has-new-commit == 'yes'

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---netbsd-9.1-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---netbsd-9.2-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---netbsd-9.3-amd64-tar-xz
          path: .


      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---openbsd-7.2-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---openbsd-7.3-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---openbsd-7.4-amd64-tar-xz
          path: .


      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---freebsd-13.0-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---freebsd-13.1-amd64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---freebsd-13.2-amd64-tar-xz
          path: .


      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---macos11.0-x86_64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---macos12.0-x86_64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---macos13.0-x86_64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---macos11.0-arm64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---macos12.0-arm64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---macos13.0-arm64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---linux-x86_64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---linux-aarch64-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---linux-ppc64le-tar-xz
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: autotools-setup---linux-s390x-tar-xz
          path: .

      - run: ls -a

      - run: |
          printf 'build-from: https://github.com/leleliu008/autotools-setup/tree/%s\n\n' ${{ needs.check.outputs.git-sha }} > notes.md
          printf 'sha256sum:\n```\n%s\n```\n' "$(sha256sum autotools-setup-*.tar.xz)" >> notes.md

          VERSION="$(ls autotools-setup-*-linux-x86_64.tar.xz | cut -d- -f3)"
          TAGNAME="$VERSION+${{ needs.check.outputs.git-sha }}"

          # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
          git -c init.defaultBranch=master init
          git remote add origin ${{ github.repositoryUrl }}

          gh release create "$TAGNAME" autotools-setup-*.tar.xz --title "$TAGNAME" --notes-file notes.md
