name: Ubuntu

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [20.04, 22.04]

    container: ubuntu:${{ matrix.version }}

    steps:
      - uses: actions/checkout@main

      - run:  apt -y update
      - run:  apt -y install cmake ninja-build pkg-config g++ linux-headers-generic  curl zip unzip tar git

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install curl openssl libgit2 libarchive libyaml jansson zlib

      - run:  |
          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/autotools-setup

      - run: ./output/bin/autotools-setup --help
      - run: ./output/bin/autotools-setup -h

      - run: ./output/bin/autotools-setup --version
      - run: ./output/bin/autotools-setup -V

      - run: ./output/bin/autotools-setup sysinfo

      - run: ./output/bin/autotools-setup env

      - run: ./output/bin/autotools-setup integrate zsh
      - run: ./output/bin/autotools-setup integrate zsh -v

      - run: ./output/bin/autotools-setup setup -v

        #- run: ./output/bin/autotools-setup upgrade-self
