name: voidlinux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  voidlinux:
    strategy:
      fail-fast: false
      matrix:
        variant: ['voidlinux', 'voidlinux-musl']

    runs-on: ubuntu-latest

    container: voidlinux/${{ matrix.variant }}

    steps:
      - run: xbps-install -Suy xbps
      - run: xbps-install -Suy cmake ninja gcc pkg-config libcurl-devel libarchive-devel libyaml-devel

      # https://github.com/actions/checkout/issues/334
      - uses: actions/checkout@v1

      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/autotools-setup

      - run: ./output/bin/autotools-setup --help
      - run: ./output/bin/autotools-setup -h

      - run: ./output/bin/autotools-setup --version
      - run: ./output/bin/autotools-setup -V

      - run: ./output/bin/autotools-setup sysinfo

      - run: ./output/bin/autotools-setup env

      - run: ./output/bin/autotools-setup integrate zsh
      - run: ./output/bin/autotools-setup integrate zsh -v

      - run: ./output/bin/autotools-setup setup -v

        #- run: ./output/bin/autotools-setup upgrade-self
