name: voidlinux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  voidlinux:
    strategy:
      fail-fast: false
      matrix:
        variant: ['voidlinux', 'voidlinux-musl']

    runs-on: ubuntu-latest

    container: voidlinux/${{ matrix.variant }}

    steps:
      - run: xbps-install -Suy xbps
      - run: xbps-install -Suy git cmake ninja gcc pkg-config libcurl-devel libarchive-devel libyaml-devel

      # https://github.com/actions/checkout/issues/334
      - uses: actions/checkout@v1

      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/autotools-setup

      - run: ./output/bin/autotools-setup --help
      - run: ./output/bin/autotools-setup -h

      - run: ./output/bin/autotools-setup --version
      - run: ./output/bin/autotools-setup -V

      - run: ./output/bin/autotools-setup sysinfo

      - run: ./output/bin/autotools-setup env

      - run: ./output/bin/autotools-setup show-default-config

      - run: ./output/bin/autotools-setup integrate zsh
      - run: ./output/bin/autotools-setup integrate zsh -v

      - run: ./output/bin/autotools-setup setup -v


      - run: |
          unset IFS

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "$*"
          }

          run() {
              echo "${COLOR_PURPLE}==>${COLOR_OFF} ${COLOR_GREEN}$@${COLOR_OFF}"
              eval "$*"
          }

          run . ~/.autotools-setup/autotools/env.sh

          run mkdir ctags
          run cd    ctags

          run git -c init.defaultBranch=master init
          run git remote add origin https://github.com/universal-ctags/ctags
          run git -c protocol.version=2 fetch --progress --depth=1 origin '+refs/heads/master:refs/remotes/origin/master'
          run git checkout --progress --force -B master refs/remotes/origin/master

          run ./autogen.sh
          run ./configure --prefix=$PWD/out
          run gmake
          run gmake install

       #- run: ./output/bin/autotools-setup upgrade-self
